# Generated by Django 2.2.5 on 2020-02-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_cost', models.IntegerField()),
                ('product_color', models.CharField(max_length=50)),
                ('product_class', models.CharField(max_length=10)),
                ('number_of_products', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
